version: "3.8"
services:

  opencv:
    image: opencv
    build:
      context: .
      args:
         - opencv_version=4.3.0
    ports:
      - "8888:8888"

  opencv-python:
    image: opencv-python
    build:
      context: .
      dockerfile: opencv-python-Dockerfile
      args:
         - opencv_version=4.3.0
    ports:
      - "8080:8888"